apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: shedyvince29/robotshop:mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-data
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: robot-shop
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017

