apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: shedyvince29/robotshop:mysql-db
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "shipping"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-data
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: robot-shop
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

