apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
        image: shedyvince29/robotshop:ratings
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mongodb"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: robot-shop
spec:
  selector:
    app: ratings
  ports:
  - port: 8080
    targetPort: 8080
