apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: shedyvince29/robotshop:shipping
        ports:
        - containerPort: 8080
        env:
        - name: CART_ENDPOINT
          value: "cart:8080"
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "shipping"
        livenessProbe:
          exec:
            command: ["sh", "-c", "ps aux | grep '[j]ava'"]
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["sh", "-c", "ps aux | grep '[j]ava'"]
          initialDelaySeconds: 10
          periodSeconds: 5
        startupProbe:
          exec:
            command: ["sh", "-c", "ps aux | grep '[j]ava'"]
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        resources:
          limits:
            cpu: "500m"
            memory: "768Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: robot-shop
spec:
  selector:
    app: shipping
  ports:
  - port: 8080
    targetPort: 8080

